/*
RouteProvider.js (context: "ShowCritTexts"). Generated code, edit with care.
Generated by Ampersand v3.5.0[branch_#228:44da3d6], build time: 08-Apr-16 08:36:09 West-Europa (zomertijd)
*/
AmpersandApp.config( function ($routeProvider) {
  $routeProvider
    .when( "/Criteria_32_and_32_Variables/:resourceId?"
         , { controller:  "Criteria_32_and_32_VariablesController"
           , templateUrl: "app/views/Criteria_32_and_32_Variables.html"
           , interfaceLabel: "Criteria and Variables" 
           }
         )
    .when( "/Debug_32_Information/:resourceId?"
         , { controller:  "Debug_32_InformationController"
           , templateUrl: "app/views/Debug_32_Information.html"
           , interfaceLabel: "Debug Information" 
           }
         )
});